// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Post_IsVideoField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Post_IsVideoField));
        
        string IMigrationMetadata.Id
        {
            get { return "201412172011053_Post_IsVideoField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
