// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class JournalMediaRating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JournalMediaRating));
        
        string IMigrationMetadata.Id
        {
            get { return "201509151647459_JournalMediaRating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
