// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Achievement_AdditionalFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Achievement_AdditionalFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201509171432327_Achievement_AdditionalFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
