// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Deleted_FeedbackComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deleted_FeedbackComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201508080017160_Deleted_FeedbackComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
