// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AchievementsTypes_IDENTITYINSERT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AchievementsTypes_IDENTITYINSERT));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241951452_AchievementsTypes_IDENTITYINSERT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
