// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Profile_NullableBirthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Profile_NullableBirthday));
        
        string IMigrationMetadata.Id
        {
            get { return "201510201014263_Profile_NullableBirthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
