// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AvhievenetsValues_DATA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AvhievenetsValues_DATA));
        
        string IMigrationMetadata.Id
        {
            get { return "201509242003337_AvhievenetsValues_DATA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
